### ISSUE TITLE
Where are the instructions for step 8

### ISSUE THREAD

**Issue by jaycbrf4** [node-girls/express-workshop#35]
Once again a tutorial that makes you copy and paste a bunch of code then leaves you hanging.

**Comment by claireinez** [comment]
Hi @jaycbrf4 -- may I ask what more you wanted in [Step 8](https://github.com/node-girls/express-workshop/blob/master/step08.md)? If there is not enough information in the README for that step, please raise an issue with more specific feedback so that we can address the problem.

**Comment by jaycbrf4** [comment]
Is there anywhere to view completed code to help me along?

**Comment by claireinez** [comment]
Our workshops are designed to lead you through from start to finish, but you are also encouraged to search online for further detail. If you really feel the instructions are not sufficient for you to complete the tutorial, you can find the solution [here](https://github.com/node-girls/express-workshop-complete). Please let us know if there is a way we can improve our workshop but I am closing this issue now because it is not constructive.
